### ISSUE TITLE
Don't depend on servant-server and servant-auth-server

### ISSUE THREAD

**Issue by domenkozar** [cachix/cachix#2]
- [x] [Move `ToJWT/FromJWT` into `servant-auth`](https://github.com/haskell-servant/servant-auth/issues/135)
- [x] [Cookie newtype wrapper for servant-auth](https://github.com/haskell-servant/servant-auth/issues/58)
- [x] [split Server part from `servant-generic` into `servant-generic-server`](https://github.com/haskell-servant/servant/pull/1003)

Stretch:
- [x] [servant-swagger-ui-core depends on servant-server](https://github.com/haskell-servant/servant-swagger-ui/issues/55)
